export const ACTUAL_BACKEND_ADDRESS = YANDEX_NODE_BACKEND_ADDRESS;
// export const LOCALHOST_BACKEND_ADDRESS = "http://localhost:8080/";
const YANDEX_NODE_BACKEND_ADDRESS = "http://51.250.101.115:8090/";
